// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiodxxoktyuarljyndjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpb2R4eG9rdHl1YXJsanluZGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDAwNzQsImV4cCI6MjA2OTE3NjA3NH0.oG6ReVL05TXCXmjTyySSZLMxZbkXAwdha728GxU2lSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});